
name: Upload a new release to PyPI

on:
  release:
    types: [created]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: "3.7"

    - name: Install poetry
      run: make download-poetry

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        source "$HOME/.poetry/env"
        poetry config virtualenvs.in-project true
        poetry install

    - name: Build and publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        source "$HOME/.poetry/env"
        poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
